en:
  languageName: EN
  languageCode: en-us
  contentDir: content/en
  params:
    hugoblox:
      identity:
        name: "Taisei Ando"
        description: "Academic homepage of Taisei Ando, Ph.D. student in Robotics at The University of Tokyo."

ja:
  languageName: JA
  languageCode: ja-jp
  contentDir: content/ja
  params:
    hugoblox:
      identity:
        name: "Taisei Ando"
